version: '3.7'
services:
 web:
   stdin_open: true
   build:
     context: .
     dockerfile: web/Dockerfile
   ports:
     - 8080:3000
   volumes:
     - "/app/node_modules"
     - "./web:/app"
   environment:
     - CHOKIDAR_USEPOLLING=true

 api:
   build:
     context: .
     dockerfile: api/Dockerfile
   ports:
     - 8081:8081
   volumes:
     - ./api:/app
   command: python3 manage.py runserver 0.0.0.0:8081
